server:
  port: 8581
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka
  register-with-eureka: true
  fetch-registry: false
spring:
  application:
    name: book-service
