server:
  port: 8580
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka
  register-with-eureka: true
  fetch-registry: true
spring:
  application:
    name: book-service